#!/bin/bash

# variables
CONTAINER=team-$1
IMAGE=chall

# create the container if it doesn't exist
if [[ ! -e /var/lib/lxd/containers/$CONTAINER ]]
  then
    lxc init $IMAGE $CONTAINER &> /dev/null 
    lxc config device add $CONTAINER eth0 nic nictype=macvlan name=eth0 parent=ens3 vlan=$1 &> /dev/null 
    lxc start $CONTAINER &> /dev/null 
    echo container $CONTAINER started
  else
    echo container $CONTAINER already created and started
fi
exit 0
